Documentation guidelines
NewDayTechnology/API-Design pull request #8
Opened 2022-05-12 08:45 UTC by DebDutta171989

Refer to the following document to understand how the document guidelines have been organised into different sections:

**ContentGuidelines.md**

2022-05-12 16:39 UTC, davidwhitney requested changes
Hey, some comments for changes before I merge this in.

- D

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/APIContentStructure.md
> +  * Authentication and Authorisation
I don't think this should be in every introduction - unless there is a *specific* requirement for that API.

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/APIContentStructure.md
> +  * Workflow diagrams: Diagramatic representation to explain the API function, if it is a part of a bigger workflow process.
I think we should be more specific here and use **sequence diagrams** otherwise we'll end up with diagrams of varying styles in our documentation.

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/APIContentStructure.md
> +  * FAQs
FAQs shouldn't be in the introduction on a per-API basis.

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/APIContentStructure.md
> +    * **API Reference**: Include the following, based on the Open API Specification version 3.0:
This should all come from the OpenAPI auto-generation tools.
We perhaps need to re-phrase this to explain that we expect those tools to be used to provide legible output.

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/APIContentStructure.md
> +* **Integration Guide**: Include the following:
I don't think this information is relevant per-API and we should have one document outlining our general approach to Versioning, Environments, and process.

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/ContentGuidelines.md
> +* **Simple easy to follow instructions**: The content must be lucid and comprehensible to our customers, including both native and non-native English speakers.
I might sound like a pedant here - but I'd prefer "The content must be simple and comprehensible" - ironically, "lucid" is probably a confusing word! :)

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/DocumentPublicationProcess.md
> +    * Create a separate branch with your team name.
I don't think we should be organising API docs by team - software moves teams more regularly than we would like here, and we should probably organise it by function for end user clarity.

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/DocumentPublicationProcess.md
> +      * **API Reference**: Contains the Open API file.
Why an extra directory here? Couldn't these just be three files in a single directory.

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/DocumentPublicationProcess.md
> +7. Mention the following flags in both the (**User Guides** and **API Reference**) document types:
This is a really weird process, let's chat about it :)

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/GenericDocumentationGuidelines.md
> +* **Keep your sentences short and crisp**: It is often difficult to understand long sentences. Hence, write simple sentences that are easier to follow.
"short and succinct"

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/StyleGuide.md
> +The aim is to present technical information in a simple manner; it must be writer agnostic.
What does "writer agnostic" mean? The information doesn't believe in writers? ;)

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/StyleGuide.md
> +* **Hurts any religious sentiment**: Do not mention any religion when you are explaining any concept or citing an example.
Agnostic! :)

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/StyleGuide.md
> +* Add comma (`,`) in the following scenarios:
In this house, we're a fan of the oxford comma!

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/StyleGuide.md
> +    * Hence
Probably just don't ever use "hence"

2022-05-12 16:39 UTC, davidwhitney commented on DocumentationGuidelines/StyleGuide.md
> +* Add full stop (`.) at the end of a complete sentence.
Missing the closing ` (backtick) here

2022-05-13 13:13 UTC, TanviND commented
Once the user guides content is ready for review and publication into Developer Portal, as a Product Owner or Tech Lead you can use the following process to get the content published :

1. Upload your markdown files (read here on how to structure your markdown files) and Open API files to the Github repository, here is a link - https://github.com/NewDayCards/NewDay.Docs.DevPortal.Content

2. Create a separate branch with your team name and upload three folders within it:

a. Introduction (markdown file): Contains the API overview information.
b. Integration guides (markdown file): Contains the API integration information.
c. API specs file: Contains the Open API file.

3. Raise a pull request and assign Deb Dutta Das (Github user name: @DebDutta171989) as a reviewer. 
Note: The content will be reviewed as per the documentation guidelines.

4. Deb may suggest amends in form of commentary and we recommend you to incorporate the comments. Raise a pull request again with revised content for Deb to review again. 

5. Once the content aligns with NewDays's style, Deb Dutta Das will approve the content request.

6. You will need to merge your branch with the main branch at this stage.

7. Once the content is merged, raise a JIRA ticket in the [Developer Portal backlog] for content to be pulled in.  (https://newdaycards.atlassian.net/jira/software/c/projects/DEVPORT/boards/1169).
 Please ensure that you mention the following flags in both the (User Guides and API Reference) document types:

PublicationReady: Specify this to publish the document in the production environment. If this flag is absent, the document is published in the User Acceptance Testing (UAT) environment.

ForExternalPublication: Specify this to publish the document in the external Developer Portal site. If this flag is absent, the document is published in the internal Developer Portal site.

*We aim to automate this process as much as possible, so please bear with us in the meantime

2022-05-23 10:18 UTC, DebDutta171989 commented on DocumentationGuidelines/ContentGuidelines.md
> +* **Simple easy to follow instructions**: The content must be lucid and comprehensible to our customers, including both native and non-native English speakers.
I agree; I have replaced 'lucid' with 'simple'.

2022-05-25 12:07 UTC, DebDutta171989 commented on DocumentationGuidelines/DocumentPublicationProcess.md
> +7. Mention the following flags in both the (**User Guides** and **API Reference**) document types:
Made changes as per discussions.

2022-05-26 14:29 UTC, DebDutta171989 commented on DocumentationGuidelines/StyleGuide.md
> +The aim is to present technical information in a simple manner; it must be writer agnostic.
Agreed. The word 'agnostic' is now removed and replaced with 'consistent style'.

2022-05-26 14:30 UTC, DebDutta171989 commented on DocumentationGuidelines/StyleGuide.md
> +* **Hurts any religious sentiment**: Do not mention any religion when you are explaining any concept or citing an example.
Agreed

2022-05-26 14:41 UTC, alefranz commented on DocumentationGuidelines/APIContentStructure.md
> +* **Integration Guide**: Include the following:
FYI I had created a library that should allow for many services to auto-populate some attributes like `Required`, `MinLength` , `MaxLength`, `Pattern`...
https://github.com/NewDayTechnology/NewDay.Extensions.FunctionsValidationFilter

I have a couple more improvements to do in it and then will share again

2022-05-27 08:34 UTC, DebDutta171989 commented on DocumentationGuidelines/StyleGuide.md
> +    * Hence
This is already there.

2022-05-27 08:34 UTC, DebDutta171989 commented on DocumentationGuidelines/StyleGuide.md
> +* Add full stop (`.) at the end of a complete sentence.
Done

2022-05-27 08:35 UTC, DebDutta171989 commented on DocumentationGuidelines/APIContentStructure.md
> +  * Authentication and Authorisation
Removed

2022-05-27 08:35 UTC, DebDutta171989 commented on DocumentationGuidelines/APIContentStructure.md
> +  * FAQs
Agreed and removed

2022-05-27 08:35 UTC, DebDutta171989 commented on DocumentationGuidelines/APIContentStructure.md
> +    * **API Reference**: Include the following, based on the Open API Specification version 3.0:
Modified

2022-05-27 08:35 UTC, DebDutta171989 commented on DocumentationGuidelines/APIContentStructure.md
> +* **Integration Guide**: Include the following:
Modified

2022-05-27 08:38 UTC, DebDutta171989 commented on DocumentationGuidelines/GenericDocumentationGuidelines.md
> +* **Keep your sentences short and crisp**: It is often difficult to understand long sentences. Hence, write simple sentences that are easier to follow.
Modified

2022-05-27 14:58 UTC, DebDutta171989 commented on DocumentationGuidelines/APIContentStructure.md
> +  * Workflow diagrams: Diagramatic representation to explain the API function, if it is a part of a bigger workflow process.
Modified.

2022-05-27 14:58 UTC, DebDutta171989 commented on DocumentationGuidelines/StyleGuide.md
> +* Add comma (`,`) in the following scenarios:
This is already covered — serial comma

2022-05-30 09:55 UTC, davidwhitney approved these changes

2022-05-30 09:57 UTC, merged